# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CompareRoads
                                 A QGIS plugin
 This plugin compares two linear shapefiles 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-03-09
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Igor Zinyaev
        email                : igor.zinyaev@yandex.ru
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction,QTableWidgetItem
from qgis.PyQt import QtWidgets
from qgis import processing


import qgis.core as core
import qgis.gui as gui
import qgis.utils as utils
from statistics import median
import datetime

advancedMode = False
relevanceMode = True


# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .compare_road_dialog import CompareRoadsDialog
import os.path


class CompareRoads:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'CompareRoads_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Compare Roads')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('CompareRoads', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/compare_road/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Compare roads'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Compare Roads'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        self.dlg = CompareRoadsDialog()
            


        # show the dialog
        
        self.dlg.mMapLayerComboBox_etalon.setFilters(core.QgsMapLayerProxyModel.LineLayer)
        self.dlg.mMapLayerComboBox_compared.setFilters(core.QgsMapLayerProxyModel.LineLayer)
        self.dlg.pushButton.clicked.connect(self.compare)
        self.dlg.checkBox_advanced.clicked.connect(self.advanced)
        self.dlg.checkBox_relevance.clicked.connect(self.relevanceMode)
        self.dlg.label_advanced_points.hide()
        self.dlg.label_advanced_buffer.hide()
        self.dlg.spinBox_advanced_buffer.hide()
        self.dlg.spinBox_advanced_points.hide()
        self.advancedMode = False
        self.dlg.tableWidget.setColumnHidden(2,False)
        self.dlg.tableWidget.resizeColumnsToContents()




        self.dlg.show()
        
    def buffer(self, DISTANCE=10):
            layer1 = self.dlg.mMapLayerComboBox_etalon.currentLayer()
            layer2 = self.dlg.mMapLayerComboBox_compared.currentLayer()
            if advancedMode == True:
                DISTANCE = self.dlg.spinBox_advanced_buffer.value()
                

            params1 = {'INPUT': layer1.name(),
               'DISTANCE': DISTANCE,
               'SEGMENTS': 10,
               'DISSOLVE': True,
               'END_CAP_STYLE': 0,
               'JOIN_STYLE': 0,
               'MITER_LIMIT': 10,
               'OUTPUT': 'TEMPORARY_OUTPUT'}
            params2 = {'INPUT': layer2.name(),
               'DISTANCE': DISTANCE+self.fieldCalculatorAccuracy(),
               'SEGMENTS': 10,
               'DISSOLVE': True,
               'END_CAP_STYLE': 0,
               'JOIN_STYLE': 0,
               'MITER_LIMIT': 10,
               'OUTPUT': 'TEMPORARY_OUTPUT'}
            result_layer_etalon = processing.run("native:buffer", params1)["OUTPUT"]
            result_layer_compared = processing.run("native:buffer", params2)["OUTPUT"]
            # core.QgsProject.instance().addMapLayer(result_layer_etalon)
            return result_layer_etalon, result_layer_compared
    def intersection(self):
        layer_buff_etalon, layer_buff_compared = self.buffer()
        params = { 'GRID_SIZE' : None, 'INPUT' : layer_buff_etalon, 'INPUT_FIELDS' : [], 'OUTPUT' : 'TEMPORARY_OUTPUT', 'OVERLAY' : layer_buff_compared, 'OVERLAY_FIELDS' : [], 'OVERLAY_FIELDS_PREFIX' : '' }
        result_layer = processing.run("native:intersection", params)["OUTPUT"]
        # core.QgsProject.instance().addMapLayer(result_layer)
        return result_layer

    def addPoints(self, DISTANCE=10):
        layer = self.dlg.mMapLayerComboBox_compared.currentLayer()
        if advancedMode == True:
                DISTANCE = self.dlg.spinBox_advanced_points.value()
        params = { 'DISTANCE' : DISTANCE, 'END_OFFSET' : 0, 'INPUT' : layer.name(), 'OUTPUT' : 'TEMPORARY_OUTPUT', 'START_OFFSET' : 0 }
        result_layer = processing.run("native:pointsalonglines", params)["OUTPUT"]
        return result_layer

    def shortestLine(self):
        layer1 = self.dlg.mMapLayerComboBox_etalon.currentLayer()
        layer2 = self.addPoints()
        params = { 'DESTINATION' : layer1.name(), 'DISTANCE' : None, 'METHOD' : 0, 'NEIGHBORS' : 1, 'OUTPUT' : 'TEMPORARY_OUTPUT', 'SOURCE' : layer2}
        result_layer = processing.run("native:shortestline", params)["OUTPUT"]
        return(result_layer)

    def fieldCalculatorAccuracy(self):
        layer = self.shortestLine()
        params = { 'FIELD_LENGTH' : 0, 'FIELD_NAME' : 'length', 'FIELD_PRECISION' : 0, 'FIELD_TYPE' : 0, 'FORMULA' : '$length', 'INPUT' : layer, 'OUTPUT' : 'TEMPORARY_OUTPUT' }
        result_layer = processing.run("native:fieldcalculator", params)["OUTPUT"]
        values = []
        for feature in result_layer.getFeatures():
            attrs = feature.attributes()
            values.append(attrs[-1])
        return round(median(values),2)
    
    def fieldCalculatorCompleteness(self):
        layer_compared = self.intersection()
        layer_etalon,buff = self.buffer()
        params1 = { 'FIELD_LENGTH' : 0, 'FIELD_NAME' : 'area', 'FIELD_PRECISION' : 0, 'FIELD_TYPE' : 0, 'FORMULA' : '$area', 'INPUT' : layer_etalon, 'OUTPUT' : 'TEMPORARY_OUTPUT' }
        params2 = { 'FIELD_LENGTH' : 0, 'FIELD_NAME' : 'area', 'FIELD_PRECISION' : 0, 'FIELD_TYPE' : 0, 'FORMULA' : '$area', 'INPUT' : layer_compared, 'OUTPUT' : 'TEMPORARY_OUTPUT' }
        result_layer_etalon = processing.run("native:fieldcalculator", params1)["OUTPUT"]
        result_layer_compared = processing.run("native:fieldcalculator", params2)["OUTPUT"]
        # core.QgsProject.instance().addMapLayer(result_layer_compared)
        # core.QgsProject.instance().addMapLayer(result_layer_etalon)
        for feature in result_layer_etalon.getFeatures():
            attrs_etalon=feature.attributes()
            area_etalon = attrs_etalon[-1]
        for feature in result_layer_compared.getFeatures():
            attrs_compared=feature.attributes()
            area_compared = attrs_compared[-1]
        completeness = float(round((area_compared/area_etalon)*100,2))
        return completeness


    

    def advanced(self):
        self.advancedMode=not self.advancedMode
        global advancedMode
        advancedMode = not advancedMode
        if self.advancedMode==True:
            self.dlg.label_advanced_points.show()
            self.dlg.label_advanced_buffer.show()
            self.dlg.spinBox_advanced_buffer.show()
            self.dlg.spinBox_advanced_points.show()
        if self.advancedMode == False:
            self.dlg.label_advanced_points.hide()
            self.dlg.label_advanced_buffer.hide()
            self.dlg.spinBox_advanced_buffer.hide()
            self.dlg.spinBox_advanced_points.hide()
        return advancedMode
    
    def relevance(self):
        layer = self.dlg.mMapLayerComboBox_compared.currentLayer()
        filepath = layer.dataProvider().dataSourceUri()
        time = os.path.getmtime(filepath)
        newtime = int((datetime.date.today() - datetime.date.fromtimestamp(time)).days / (365.25 / 12))
        return newtime
    
    def relevanceMode(self):
        global relevanceMode
        relevanceMode = not relevanceMode
        if relevanceMode == True:
            self.dlg.tableWidget.setColumnHidden(2,False)
        else:
            self.dlg.tableWidget.setColumnHidden(2,True)
    
    

    def compare(self):
        self.dlg.tableWidget.setItem(0,0,QtWidgets.QTableWidgetItem(str(self.fieldCalculatorAccuracy())))
        self.dlg.tableWidget.setItem(0,1,QtWidgets.QTableWidgetItem(str(self.fieldCalculatorCompleteness())))
        if relevanceMode == True:
            self.dlg.tableWidget.setItem(0,2,QtWidgets.QTableWidgetItem(str(self.relevance())))






            

